      - name: Install Tools Sakti
        run: |
          sudo apt-get update
          # Kita hapus 'img2simg' dari daftar install karena sudah ada di dalam android-sdk-libsparse-utils
          sudo apt-get install -y erofs-utils p7zip-full wget android-sdk-libsparse-utils

      - name: Download & Extract GSI
        run: |
          # Pakai -q biar log-nya gak penuh sama progress bar
          wget -q -O gsi_archive.7z "https://sourceforge.net/projects/misterztr-gsi/files/LineageOS/Android%2016/LineageOS-23.0-20260109-GAPPS-EROFS-GSI.7z/download"
          7z x gsi_archive.7z -ooutput_img
          GSI_IMG=$(find output_img -name "*.img")
          mv "$GSI_IMG" input_gsi.img

      - name: Unpack EROFS
        run: |
          mkdir folder_isi
          sudo fsck.erofs --extract=folder_isi input_gsi.img

      - name: Injeksi Kedaulatan KLOS
        run: |
          # Pastikan build.prop bisa diedit
          sudo chmod 644 folder_isi/system/build.prop
          sudo sed -i 's/ro.build.display.id=.*/ro.build.display.id=KLOS-V16-NATIVE-BOS/g' folder_isi/system/build.prop
          echo "ro.klos.version=V16-NATIVE" | sudo tee -a folder_isi/system/build.prop
          echo "ro.klos.ai=Xenom-Core" | sudo tee -a folder_isi/system/build.prop

      - name: Repack EROFS (The "Beas" Way)
        run: |
          # Menggunakan mkfs.erofs terbaru di Ubuntu
          sudo mkfs.erofs -zlz4hc -T 0 --mount-point /system klos_v16_raw.img folder_isi/

      - name: Convert to Sparse (Fix Command)
        run: |
          # Perintah tetap img2simg, tapi sekarang paketnya sudah benar
          img2simg klos_v16_raw.img klos_v16_sparse.img

      - name: Upload Kedaulatan
        uses: actions/upload-artifact@v4
        with:
          name: KLOS-V16-GSI-PocoM5
          path: klos_v16_sparse.img
          
